version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Backup.settings
      - PYTHONUNBUFFERED=1
