version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./backups:/app/backups
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "80:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Backup.settings
      - PYTHONUNBUFFERED=1
      - DB_NAME=backup_db
      - DB_USER=backup_user
      - DB_PASSWORD=Anas2108@@
      - DB_HOST=mariadb
      - DB_PORT=33006
    depends_on:
      - mariadb
      #- rabbitmq

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Anas2108@@
      MYSQL_DATABASE: backup_db
      MYSQL_USER: backup_user
      MYSQL_PASSWORD: Anas2108@@
    ports:
      - "33006:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mariadb_network

  ftp-server:
    image: fauria/vsftpd
    container_name: ftp-server
    environment:
      - FTP_USER=BackuPro
      - FTP_PASS=Anas2108@@
      - FTP_DIRECTORY=/opt/BackupPro/backups
    volumes:
      - ./backups:/opt/BackupPro/backups
      - ./vsftpd.conf:/etc/vsftpd.conf
    ports:
      - "21:21"
    restart: always
#  rabbitmq:
#    image: rabbitmq:3-management
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_DEFAULT_USER: julio
#      RABBITMQ_DEFAULT_PASS: backuppro
#
#  celery:
#    build: .
#    command: celery -A Backup worker --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - rabbitmq
#
#  celery_beat:
#    build: .
#    command: celery -A Backup beat --loglevel=info
#    volumes:
#      - .:/app
#    depends_on:
#      - rabbitmq

volumes:
  db_data:

networks:
  mariadb_network: