version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ./db.sqlite3x:/app/db.sqlite3x
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=Backup.settings
      - PYTHONUNBUFFERED=1

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Porta do broker RabbitMQ
      - "15672:15672"  # Porta da interface de gerenciamento do RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: julio
      RABBITMQ_DEFAULT_PASS: backuppro

  celery:
    build: .
    command: celery -A Backup worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq


  celery_beat:
    build: .
    command: celery -A Backup beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
