# Generated by Django 4.2.16 on 2024-11-08 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_nome_manufacturer_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('52eb49c6-b51a-41d7-8910-47888d6e6718'), editable=False, primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
        ),
        migrations.AddField(
            model_name='enterprise',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.UUIDField(default=uuid.UUID('44892d93-545a-49c6-9bfa-9bb6c96d0cb9'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd063dbc-3cd0-4850-8e23-3f1e2221d714'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ScriptEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7dcda9c6-f6e9-442a-820b-5553ad003924'), editable=False, primary_key=True, serialize=False)),
                ('Script', models.TextField(blank=True, null=True, verbose_name='Script do Backup')),
                ('modelEquipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelequipment')),
            ],
        ),
        migrations.AddField(
            model_name='modelequipment',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.manufacturer'),
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Nome do equipamento')),
                ('version', models.CharField(max_length=10, verbose_name='Versao')),
                ('backup', models.CharField(choices=[('Sim', 'Active'), ('Não', 'Inactive')], default='Sim', max_length=20)),
                ('QtdBackup', models.IntegerField(verbose_name='Backups diários')),
                ('UltimoBackup', models.DateTimeField(verbose_name='Data Ultimo Backup')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enterprise')),
                ('modelEquipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelequipment')),
            ],
        ),
    ]
