# Generated by Django 4.2.16 on 2024-11-08 12:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelequipment_enterprise_email_alter_enterprise_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1422ba5a-7eb6-49d5-9ccb-239aaf508956'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e4f233ef-77bf-4591-9c18-5832a63b7118'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelequipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('741d3d74-b0a7-4644-a108-b4eb1f214c8f'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scriptequipment',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cc662652-9853-416c-a335-ac7fbea51a69'), editable=False, primary_key=True, serialize=False),
        ),
    ]
