# Generated by Django 4.2.16 on 2024-11-08 13:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_enterprise_id_alter_manufacturer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP de acesso'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='portaacesso',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Porta SSh'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='senhaacesso',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Senha de acesso'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='usuarioacesso',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Usuário de acesso'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scriptequipment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
