# Generated by Django 4.2.16 on 2024-11-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_equipment_ip_equipment_portaacesso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='core.enterprise', verbose_name='Propretário'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='modelEquipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modelequipment', verbose_name='Modelo'),
        ),
    ]
