# Generated by Django 4.2.16 on 2024-11-21 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enterprise_usuario_alter_equipment_enterprise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enterprise',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipamento', 'verbose_name_plural': 'Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Fabricánte', 'verbose_name_plural': 'Fabricántes'},
        ),
        migrations.AlterModelOptions(
            name='modelequipment',
            options={'verbose_name': 'Modelo de Equipamento', 'verbose_name_plural': 'Modelo de Equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='scriptequipment',
            options={'verbose_name': 'Script', 'verbose_name_plural': 'Scripts'},
        ),
        migrations.AddField(
            model_name='equipment',
            name='ScriptEquipment',
            field=models.ForeignKey(default='1db5796166b34da1a3f7828c7469c506', on_delete=django.db.models.deletion.CASCADE, to='core.scriptequipment', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='enterprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamento', to='core.enterprise', verbose_name='Proprietário'),
        ),
    ]
