# Generated by Django 4.2.16 on 2024-11-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_enterprise_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='ScriptEquipment',
            field=models.ForeignKey(default='1db5796166b34da1a3f7828c7469c506', on_delete=django.db.models.deletion.CASCADE, to='core.scriptequipment', verbose_name='Script'),
        ),
    ]
