# Generated by Django 4.2.16 on 2024-11-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_equipment_scriptequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='UltimoBackup',
            field=models.DateTimeField(verbose_name='Data Último Backup'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='portaacesso',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Porta SSH'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Versão'),
        ),
    ]
