# Generated by Django 4.2.16 on 2024-11-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_equipment_ultimobackup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='backups/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_files', to='core.equipment')),
            ],
            options={
                'verbose_name': 'Arquivo de Backup',
                'verbose_name_plural': 'Arquivos de Backup',
            },
        ),
    ]
