# Generated by Django 4.2.16 on 2024-11-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_backupfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='access_type',
            field=models.CharField(choices=[('Telnet', 'Telnet'), ('SSH', 'SSH')], default='SSH', max_length=10, verbose_name='Tipo de Acesso'),
        ),
    ]
