# Generated by Django 4.2.16 on 2024-11-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_equipment_access_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='HoraBackup',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do Backup'),
        ),
    ]
