# Generated by Django 4.2.16 on 2024-11-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_equipment_horabackup_equipment_horariobackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='HorarioBackup',
            field=models.TimeField(choices=[('00:00:00', '00:00:00'), ('03:00:00', '03:00:00'), ('06:00:00', '06:00:00'), ('12:00:00', '12:00:00'), ('18:00:00', '18:00:00')], default='00:00:00', verbose_name='Horário do Backup'),
        ),
    ]
