# Generated by Django 4.2.16 on 2024-11-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_equipment_horariobackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='HorarioBackup',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='QtdBackup',
        ),
    ]
