# Generated by Django 4.2.16 on 2024-11-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_equipment_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='ativo',
            field=models.CharField(choices=[('Sim', 'Active'), ('Não', 'Inactive')], default='Sim', max_length=20, verbose_name='Status'),
        ),
    ]
