# Generated by Django 4.2.16 on 2024-11-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enterprise_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='ativo',
            field=models.CharField(choices=[('Sim', 'Ativo'), ('Não', 'Desativado')], default='Sim', max_length=20, verbose_name='Status'),
        ),
    ]
