# Generated by Django 4.2.16 on 2024-12-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_enterprise_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='horario_backup',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='ip_ssh',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='porta_ssh',
            field=models.IntegerField(default=22),
        ),
    ]
