# Generated by Django 4.2.16 on 2024-12-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_enterprise_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='horario_backup',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
