# Generated by Django 4.2.16 on 2024-12-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_enterprise_horario_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='horario_backup',
            field=models.TimeField(),
        ),
    ]
