# Generated by Django 4.2.16 on 2024-12-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_enterprise_horario_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='horario_backup',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
